// <auto-generated />
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ApoyoContext))]
    partial class ApoyoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidad.Apoyo", b =>
                {
                    b.Property<string>("Idapoyo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonaCedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tipoapoyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Vrapoyo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Idapoyo");

                    b.HasIndex("PersonaCedula");

                    b.ToTable("Apoyos");
                });

            modelBuilder.Entity("Entidad.Persona", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Entidad.Apoyo", b =>
                {
                    b.HasOne("Entidad.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaCedula");
                });
#pragma warning restore 612, 618
        }
    }
}
